[project]
name = "app1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataset>=1.6.2",
    "fastapi>=0.116.1",
    "psycopg2-binary>=2.9.10",
    "redis>=6.4.0",
    "uvicorn>=0.35.0",
]
