name: main-ci-actions

on: [push]
jobs:
  sast_scan:
    name: scan with bandit
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: install python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.12
      - name: install bandit
        run: pip3 install bandit
      - name: scan app1
        run: bandit -i ./app1 -f json -o ./app1/bandit-reports.json
      - name: scann app2
        run: bandit -i ./app1 -f json -o ./app2/bandit-reports.json
      - name: uplozd artifacts:
        uses: actions/upload-artifact@v4.6.2
        with:
          name: upload bandit reports
          path: ./app1/bandit-reports.json
      - name: download  artefacts
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo-url: "http://31.187.72.141:8080/"
          defectdojo-username: admin
          defectdojo-password: kvXax70pLk3pkphaRoQKe4
          scan-results-file-name: ./app1/bandit-reports.json
          defectdojo-product: fastline
          
          
    
